name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "ðŸš€ deploy"
    runs-on: ubuntu-latest
    env:
      VPS_SSH_DESTINATION: ${{ vars.VPS_SSH_DESTINATION }}
      VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
      VPS_DEPLOY_DIR: ~/${{ github.repository }}/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.VPS_SSH_KEY }}

      - name: Copy files to VPS
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude='.git*' ./ ${{ env.VPS_SSH_DESTINATION }}:${{ env.VPS_DEPLOY_DIR }}

      - name: Deploy with Podman Compose
        run: >
          ssh -o StrictHostKeyChecking=no ${{ env.VPS_SSH_DESTINATION }} "
          cd ${{ env.VPS_DEPLOY_DIR }}
          && podman compose up --force-recreate --build -d 
          && podman image prune -f"
